# Generated by Django 4.0.3 on 2024-06-15 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0003_customer_active'),
        ('emailtemplate', '0006_alter_emailtemplate_signatures'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRouteSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date_time', models.DateTimeField()),
                ('schedule_route_id', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('schedule', 'Schedule'), ('sent', 'Sent')], default='schedule', max_length=250)),
                ('schedule_customer', models.ManyToManyField(to='customer.customer')),
                ('schedule_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailtemplate.emailtemplate')),
            ],
        ),
    ]
