# Generated by Django 4.0.3 on 2023-10-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(max_length=100)),
                ('CompanyName', models.CharField(max_length=100)),
                ('CompanyPhone', models.CharField(max_length=15)),
                ('RatesEmail', models.EmailField(max_length=254)),
                ('BillingEmail', models.EmailField(max_length=254)),
                ('LegalEmail', models.EmailField(max_length=254)),
                ('ManagerName', models.CharField(max_length=100)),
                ('ManagerEmail', models.EmailField(max_length=254)),
                ('ManagerPhone', models.CharField(max_length=15)),
                ('Status', models.CharField(default='Active', max_length=10)),
                ('DND', models.BooleanField(default=False)),
            ],
        ),
    ]
