# Generated by Django 4.0.3 on 2024-05-20 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='BillingEmail',
            new_name='billing_email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='CompanyName',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='CompanyPhone',
            new_name='company_phone',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='CustomerName',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='DND',
            new_name='dnd',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='LegalEmail',
            new_name='legal_email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='ManagerEmail',
            new_name='manager_email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='ManagerName',
            new_name='manager_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='ManagerPhone',
            new_name='manager_phone',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='RatesEmail',
            new_name='rates_email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Status',
            new_name='status',
        ),
    ]
