# Generated by Django 4.0.3 on 2024-05-28 08:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management_profile', '0001_initial'),
        ('customer', '0003_customer_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRateTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_name', models.CharField(max_length=255)),
                ('customer_prefix', models.CharField(max_length=200)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('rate_status', models.CharField(max_length=20)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('rate_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_profile.managementprofilename')),
            ],
        ),
    ]
