# Generated by Django 4.0.3 on 2024-06-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_rate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerratetable',
            name='rate_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
