# Generated by Django 4.0.3 on 2024-06-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_rate', '0002_alter_customerratetable_rate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerratetable',
            name='customer_prefix',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
