# Generated by Django 4.0.3 on 2024-06-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toproutes', '0002_alter_route_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='top_route_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
