# Generated by Django 4.0.3 on 2024-06-26 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendorratetabel', '0001_initial'),
        ('vendorrate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorrate',
            name='vendor_rate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendorratetabel.vendorratetabel'),
        ),
    ]
