# Generated by Django 4.0.3 on 2024-06-24 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('company_phone', models.CharField(max_length=15)),
                ('rates_email', models.EmailField(max_length=254)),
                ('billing_email', models.EmailField(max_length=254)),
                ('legal_email', models.EmailField(max_length=254)),
                ('manager_name', models.CharField(max_length=100)),
                ('manager_email', models.EmailField(max_length=254)),
                ('manager_phone', models.CharField(max_length=15)),
                ('status', models.CharField(default='Active', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('dnd', models.BooleanField(default=False)),
                ('country_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.countrycode')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
