# Generated by Django 4.0.3 on 2024-06-26 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
        ('companycustomer', '0002_customer_manager_phone_country_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='manager_phone_country_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers_manager_phone_country_code', to='country.countrycode'),
        ),
    ]
