# Generated by Django 4.0.3 on 2024-06-29 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companycustomer', '0003_alter_customer_manager_phone_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='company_name',
        ),
    ]
