# Generated by Django 4.0.3 on 2024-06-26 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management_profile', '0001_initial'),
        ('companycustomer', '0003_alter_customer_manager_phone_country_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorRateTabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_rate_name', models.CharField(max_length=200, unique=True)),
                ('vendor_prefix', models.CharField(max_length=200, unique=True)),
                ('created_date', models.DateField(auto_now=True)),
                ('rate_status', models.BooleanField(default=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companycustomer.customer')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor_rate_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_profile.managementprofilename')),
            ],
        ),
    ]
