# Generated by Django 4.0.3 on 2024-05-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratetabel',
            name='rate_status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ratetabel',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
