# Generated by Django 4.0.3 on 2024-06-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_alter_ratetabel_rate_status_alter_ratetabel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratetabel',
            name='billing_increment_1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ratetabel',
            name='billing_increment_n',
            field=models.IntegerField(),
        ),
    ]
