# Generated by Django 4.0.3 on 2024-06-28 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myusersession', '0002_companyuser_parent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='parent_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
    ]
