# Generated by Django 4.0.3 on 2024-06-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myusersession', '0005_alter_companyuser_parent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='company_admin',
            field=models.BooleanField(default=False),
        ),
    ]
