# Generated by Django 4.0.3 on 2024-06-29 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myusersession', '0006_companyuser_company_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyuser',
            old_name='company_name',
            new_name='user_name',
        ),
    ]
