# Generated by Django 4.0.3 on 2024-06-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myusersession', '0007_rename_company_name_companyuser_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='company_name',
            field=models.CharField(default='TruLynx', max_length=300),
        ),
    ]
