# Generated by Django 4.0.3 on 2024-06-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myusersession', '0008_companyuser_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='company_name',
            field=models.CharField(max_length=300),
        ),
    ]
