# Generated by Django 4.0.3 on 2023-10-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('TemplateID', models.AutoField(primary_key=True, serialize=False)),
                ('TemplateName', models.CharField(max_length=100)),
                ('TemplateMessage', models.CharField(max_length=255)),
                ('TemplateBody', models.TextField()),
                ('Status', models.CharField(default='Active', max_length=10)),
                ('CreatedDateTime', models.DateTimeField(auto_now_add=True)),
                ('LastUpdatedDateTime', models.DateTimeField(auto_now=True)),
                ('CCTO', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
