# Generated by Django 4.0.3 on 2024-06-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailtemplate', '0002_emailtemplate_template_body_after_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_body_after',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_body_before',
            field=models.TextField(),
        ),
    ]
