# Generated by Django 4.0.3 on 2024-06-12 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailtemplate', '0003_alter_emailtemplate_template_body_after_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailtemplate',
            old_name='TemplateMessage',
            new_name='TemplateSubject',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='TemplateBody',
        ),
    ]
