# Generated by Django 4.0.3 on 2024-06-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailtemplate', '0004_rename_templatemessage_emailtemplate_templatesubject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='signatures',
            field=models.CharField(default='Thanks & Regard', max_length=200),
        ),
    ]
