# Generated by Django 4.0.3 on 2024-06-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailtemplate', '0005_emailtemplate_signatures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='signatures',
            field=models.CharField(max_length=200),
        ),
    ]
