# Generated by Django 4.0.3 on 2024-06-24 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companycustomer', '0001_initial'),
        ('emailtemplate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('attachement', models.FileField(blank=True, null=True, upload_to='email_attachments/')),
                ('customer_id', models.ManyToManyField(to='companycustomer.customer')),
                ('template_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailtemplate.emailtemplate')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
