# Generated by Django 4.0.3 on 2023-10-12 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('emailtemplate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('LogID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Attachment', models.FileField(blank=True, null=True, upload_to='email_attachments/')),
                ('CompanyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('TemplateID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailtemplate.emailtemplate')),
            ],
        ),
    ]
