# Generated by Django 4.0.3 on 2024-05-27 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emaillog', '0002_remove_emaillog_companyid_emaillog_customerid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emaillog',
            old_name='Attachment',
            new_name='attachement',
        ),
        migrations.RenameField(
            model_name='emaillog',
            old_name='CustomerId',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='emaillog',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='emaillog',
            old_name='LogID',
            new_name='log_id',
        ),
        migrations.RenameField(
            model_name='emaillog',
            old_name='TemplateID',
            new_name='template_id',
        ),
    ]
