# Generated by Django 4.0.3 on 2024-06-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_minutes',
            field=models.IntegerField(default=30),
        ),
    ]
