# Generated by Django 4.0.3 on 2024-06-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoice_invoice_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_minutes',
            field=models.IntegerField(),
        ),
    ]
